# TUGAS
## Pengenalan Array dengan Numpy

Kelompok

1. Muhammad Gumelar Fajari

2. Putri Ayuningsih

3. Ridho Aji Gumilang

4. Shafira Maulidina

5. Zakky Muhammad Anugrah

In [22]:
# import libraries
import numpy as np

# Membuat matriks 2x3 dengan tipe data int64
arr = np.array([[1, 2, 3], [5, 6, 7]], dtype=np.int64)

# Mencetak matriks
print("Matriks arr:")
print(arr)

# Mencetak bentuk matriks
print("Bentuk arr:", arr.shape)

# Mencetak tipe data matriks
print("Tipe data arr:", arr.dtype)

Matriks arr:
[[1 2 3]
 [5 6 7]]
Bentuk arr: (2, 3)
Tipe data arr: int64


In [23]:
# Membuat matriks 2x3 dengan tipe data int64 dan nilai elemen acak
arr_rdm = np.random.randint(0, 100, size=(2, 3), dtype=np.int64)

# Mencetak matriks arr_rdm
print("Matriks arr_rdm:")
print(arr_rdm)

# Mencetak bentuk matriks arr_rdm
print("Bentuk arr_rdm:", arr_rdm.shape)

# Mencetak tipe data matriks arr_rdm
print("Tipe data arr_rdm:", arr_rdm.dtype)


Matriks arr_rdm:
[[49 12 27]
 [37 97 58]]
Bentuk arr_rdm: (2, 3)
Tipe data arr_rdm: int64


# Aritmatika Dasar dengan Numpy

In [24]:
# Operasi penjumlahan arr dan arr_rdm
addition_result = arr + arr_rdm

# Operasi pengurangan arr dan arr_rdm
subtraction_result = arr - arr_rdm

# Operasi perpangkatan dua arr_rdm
power_of_two_result = arr_rdm ** 2

# Operasi perkalian elemen arr dan arr_rdm
elementwise_multiplication_result = arr * arr_rdm

# Transpose matriks arr_rdm
transposed_arr_rdm = arr_rdm.T

# Operasi perkalian matriks arr dan arr_rdm (dot product)
matrix_multiplication_result = np.dot(arr, arr_rdm.T)  # Perbaikan di sini

# Mencetak hasil operasi
print("Hasil penjumlahan arr dan arr_rdm:")
print(addition_result)

print("Hasil pengurangan arr dan arr_rdm:")
print(subtraction_result)

print("Hasil perpangkatan dua arr_rdm:")
print(power_of_two_result)

print("Hasil perkalian elemen arr dan arr_rdm:")
print(elementwise_multiplication_result)

print("Transpose matriks arr_rdm:")
print(transposed_arr_rdm)

print("Hasil perkalian matriks arr dan arr_rdm (dot product):")
print(matrix_multiplication_result)


Hasil penjumlahan arr dan arr_rdm:
[[ 50  14  30]
 [ 42 103  65]]
Hasil pengurangan arr dan arr_rdm:
[[-48 -10 -24]
 [-32 -91 -51]]
Hasil perpangkatan dua arr_rdm:
[[2401  144  729]
 [1369 9409 3364]]
Hasil perkalian elemen arr dan arr_rdm:
[[ 49  24  81]
 [185 582 406]]
Transpose matriks arr_rdm:
[[49 37]
 [12 97]
 [27 58]]
Hasil perkalian matriks arr dan arr_rdm (dot product):
[[ 154  405]
 [ 506 1173]]


In [25]:
# Matriks arr
arr = np.array([[1, 2, 3], [5, 6, 7]], dtype=np.int64)

# Menghitung nilai rata-rata seluruh matriks arr
mean_arr = np.mean(arr)

# Menghitung nilai rata-rata per baris matriks arr
mean_per_row = np.mean(arr, axis=1)

# Menghitung total nilai seluruh elemen matriks arr
total_sum = np.sum(arr)

# Menghitung nilai maksimum per kolom matriks arr
max_per_column = np.max(arr, axis=0)

# Mencetak hasil
print("Nilai rata-rata seluruh matriks arr:", mean_arr)
print("Nilai rata-rata per baris matriks arr:", mean_per_row)
print("Total nilai seluruh elemen matriks arr:", total_sum)
print("Nilai maksimum per kolom matriks arr:", max_per_column)


Nilai rata-rata seluruh matriks arr: 4.0
Nilai rata-rata per baris matriks arr: [2. 6.]
Total nilai seluruh elemen matriks arr: 24
Nilai maksimum per kolom matriks arr: [5 6 7]


# Fitur pada Numpy

In [26]:
# Membuat array arrg dengan nilai range 1-20
arrg = np.arange(1, 21)

# Mencetak array arrg
print("Array arrg:", arrg)

# Mencetak nilai arrg pada index 5
print("Nilai arrg index 5:", arrg[5])

# Mencetak nilai arrg untuk 3 elemen dari belakang
print("3 elemen dari belakang:", arrg[-3:])

# Mencetak nilai arrg dari indeks 3 sampai 6 (indeks 3, 4, 5, dan 6)
print("Nilai arrg dari indeks 3 sampai 6:", arrg[3:7])


Array arrg: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Nilai arrg index 5: 6
3 elemen dari belakang: [18 19 20]
Nilai arrg dari indeks 3 sampai 6: [4 5 6 7]


In [27]:
# Matriks arr
arr = np.array([[1, 2, 3], [5, 6, 7]], dtype=np.int64)

# Mencetak matriks arr
print("Matriks arr:")
print(arr)

# Slicing matriks arr untuk menghasilkan output pertama
sliced_arr1 = arr[:, 1:]

# Mencetak hasil slicing pertama
print("Sliced arr (output pertama):")
print(sliced_arr1)

# Slicing matriks arr untuk menghasilkan output kedua
sliced_arr2 = arr[:, 2:]

# Mencetak hasil slicing kedua
print("Sliced arr (output kedua):")
print(sliced_arr2)


Matriks arr:
[[1 2 3]
 [5 6 7]]
Sliced arr (output pertama):
[[2 3]
 [6 7]]
Sliced arr (output kedua):
[[3]
 [7]]


In [28]:
# Membuat matriks 3x4 dengan tipe data int64 dan nilai elemen acak
mtx_rdm = np.random.randint(0, 100, size=(3, 4), dtype=np.int64)

# Mencetak bentuk matriks mtx_rdm
print("Bentuk mtx_rdm sebelum perubahan:", mtx_rdm.shape)

# Mengubah bentuk matriks mtx_rdm menjadi satu dimensi
mtx_rdm_1d = mtx_rdm.flatten()

# Mencetak bentuk matriks mtx_rdm setelah menjadi satu dimensi
print("Bentuk mtx_rdm setelah menjadi satu dimensi:", mtx_rdm_1d.shape)

# Mengubah bentuk matriks mtx_rdm menjadi 6x2
mtx_rdm_6x2 = mtx_rdm.reshape(6, 2)

# Mencetak bentuk matriks mtx_rdm setelah menjadi 6x2
print("Bentuk mtx_rdm setelah menjadi 6x2:", mtx_rdm_6x2.shape)


Bentuk mtx_rdm sebelum perubahan: (3, 4)
Bentuk mtx_rdm setelah menjadi satu dimensi: (12,)
Bentuk mtx_rdm setelah menjadi 6x2: (6, 2)
